# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('reported', models.BooleanField()),
                ('creation_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
